flags:
  convert_audio: true
  convert_mvad: true
  convert_artifacts: true
  create_index: true
  yt_data_specific: true
  run_cleanup: false
  cleanup_dry_run: false

paths:
  audio_base: /mnt/weka/data2/yt_data/wyndlabs_1M/audio_tarred/en
  input_base: /mnt/weka/data2/yt_data/wyndlabs_1M/processed-v4-pipeline-vad_ws_continuous_en
  output_base: /mnt/weka/data-wsds/wyndlabs_1M-en/

segmentation_type: v4-vad_ws_continuous

subdirs:
  - acoustic_scores_raw
  - transcription_wslang_turbo_raw
  - pquality_wmusic_scores_raw
  - dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder
  - dtok_v2_ml_50hz_32x16384_graphemes_key16k
